import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div id="container">
      <Head>
        <title>Posible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.container}>
          <div className={styles.headlineContainer}>
            <div className={styles.headline}>
              Impulsar el cambio que buscas es
            </div>
            <div className={styles.headlineLogo}>Posible.</div>
          </div>
          <div className={styles.subheadline}>
            Ayudamos a organizaciones a crear soluciones que transformen la
            sociedad con tecnología, innovación y marketing.
          </div>
        </div>
        <div className={styles.projects}>
          <div className={styles.projectsItem}>
            <div>
              <div className={styles.title}>
                Cocreación de proyectos digitales centrados en las personas
              </div>
              <div className={styles.description}>
                Nos especializamos en educación, igualdad de género y reducción
                de desigualdades.
              </div>
            </div>
          </div>
          <div className={styles.projectsItem}>
            <div></div>
            <div>
              <div className={styles.title}>
                Programas educativos de transformación digital
              </div>
              <div className={styles.description}>
                Aprende haciendo. Todos nuestros cursos se centran en ser
                prácticos y de aplicación rápida.
              </div>
            </div>
          </div>
        </div>
      </Layout>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
